version: "3.1"

services:

  postgres_crm_service:
    container_name: postgres_crm_service
    healthcheck:
      test: 'pg_isready -h localhost -p 5432 -q -U root -d crm_service'
      interval: 3s
      timeout: 5s
      retries: 5
    image: postgres:15
    environment:
      POSTGRES_DB: crm_service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - /var/lib/postgresql/data/
    restart: always

  crm_service:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: bash /code/docker-entrypoint-dev.sh
    container_name: crm_service
    image: crm_service
    volumes:
      - .:/code
    ports:
      - "8002:8080"
    depends_on:
      - postgres_crm_service
    environment:
      ALLOWED_HOSTS: localhost,127.0.0.1,crmservice.kupfer.service.local
      CORS_ORIGIN_WHITELIST: localhost,127.0.0.1
      DATABASE_ENGINE: "postgresql"
      DATABASE_NAME: "crm_service"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root"
      DATABASE_HOST: "postgres_crm_service"
      DATABASE_PORT: "5432"
      DEBUG: "True"
      STATIC_ROOT: /static/
      JWT_PRIVATE_KEY_RSA_CRMSERVICE: |-
        -----BEGIN RSA PRIVATE KEY-----
        MIIBOgIBAAJBAMtUe741n497BS4syFvey617qA+b4DQSyHj4xE0ZH5qRuk/A42i5
        zUJidSkFs1Wvq9ShOamST1vrmHriBrYYu7MCAwEAAQJBAI2hUXiSvYwh8t/RDdcA
        f/tdkRkeSLO9CatKDOJvR5ZQAL5+7iNHTMGOC2FCU3WKSdlEo/xW3kD6omYbIWPk
        hXECIQD58w4Zl3FSaoWBhBmmyJF08cOQP2Z8amewd70LV0LNlQIhANBAhrTxnDG2
        KprAffkxjcrV/6ZWC5kGqckTNUUhf0InAiBbosNpmH8gYxM9L4wj/GZvhG9ZRBUz
        yeLn7I4vSTehnQIgJEaZMHvF0YMB+OL/DqFrKaINXlQuwQFAIh6OcPRczpECICpM
        q/qlwzGMpOD6blcWDUqgS6HXpS73To/F8RE56FP+
        -----END RSA PRIVATE KEY-----
      JWT_PUBLIC_KEY_RSA_CRMSERVICE: |-
        -----BEGIN PUBLIC KEY-----
        MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMtUe741n497BS4syFvey617qA+b4DQS
        yHj4xE0ZH5qRuk/A42i5zUJidSkFs1Wvq9ShOamST1vrmHriBrYYu7MCAwEAAQ==
        -----END PUBLIC KEY-----
      JWT_PUBLIC_KEY_RSA_BIFROST: |-
        -----BEGIN PUBLIC KEY-----
        MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALFc9NFZaOaSwUMPNektbtJqEjYZ6IRB
        qhqvJu1hKPYn9HYd75c0gIDYHJ9lb7QwQvg44aO27104rDK0xSstzL0CAwEAAQ==
        -----END PUBLIC KEY-----
      JWT_ISSUER: "buildly"
      SEARCH_SERVICE_URL: "http://searchservice.local:8001"
      DJANGO_SUPERUSER_EMAIL: "admin@buildly.io"
      DJANGO_SUPERUSER_USERNAME: "admin"
      DJANGO_SUPERUSER_PASSWORD: "admin"
      SECRET_KEY: "secret here"
      TOKEN_SECRET: "secret here"
