# Generated by Django 5.1.5 on 2025-01-23 16:27

import contact.validators
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS hstore;"),
        migrations.AlterField(
            model_name='contact',
            name='addresses',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), blank=True, help_text="List of 'address' objects with the structure: type (string - Choices: home, billing, business, delivery, mailing),street (string), house_number (string), postal_code: (string), city (string), country (string)", null=True, size=None, validators=[contact.validators.validate_addresses]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), blank=True, help_text="List of 'email' objects with the structure: type (string - Choices: office, private, other), email (string ", null=True, size=None, validators=[contact.validators.validate_emails]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phones',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.hstore.HStoreField(), blank=True, help_text="List of 'phone' objects with the structure: type (string - Choices: office, mobile, home, fax), number (string)", null=True, size=None, validators=[contact.validators.validate_phones]),
        ),
    ]
