# Generated by Django 5.1.5 on 2025-03-10 07:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_employer_contact_preferred_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('phone', 'Phone'), ('mail', 'Mail')], max_length=30), blank=True, help_text='Contact preferences as a JSON object', null=True, size=None),
        ),
    ]
