# Generated by Django 5.1.5 on 2025-01-21 14:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='uuid',
            new_name='appointment_uuid',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='organization_uuid',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='siteprofile_uuid',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='workflowlevel2_uuids',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='invitee_uuids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, help_text='List of Users invited to the appointment.', null=True, size=None),
        ),
    ]
