# Generated by Django 5.1.5 on 2025-04-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="list_type",
            field=models.CharField(
                choices=[
                    ("community", "Community"),
                    ("list", "List"),
                    ("group", "Group"),
                ],
                default="list",
                max_length=20,
            ),
        ),
    ]
