# Generated by Django 5.1.5 on 2025-04-04 09:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_list_list_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="list_uuid",
            field=models.UUIDField(
                default=uuid.UUID("edf1c383-4ff1-4dff-a21d-0e327eeb6172"),
                editable=False,
                unique=True,
            ),
        ),
    ]
