# Generated by Django 5.1.5 on 2025-04-04 09:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0003_list_list_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="list_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
