# Generated by Django 5.1.5 on 2025-04-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0004_alter_list_list_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="open_polls",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="list",
            name="pending_engagements",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
