# Generated by Django 5.1.5 on 2025-04-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0005_list_open_polls_list_pending_engagements"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="organization_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
