# Generated by Django 5.1.5 on 2025-04-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0006_list_organization_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="contact_objects",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
